export const googleIconsMap = {
  "01d": "https://maps.gstatic.com/weather/v1/sunny.svg",
  "01n": "https://maps.gstatic.com/weather/v1/clear.svg",
  "02d": "https://maps.gstatic.com/weather/v1/partly_cloudy.svg",
  "02n": "https://maps.gstatic.com/weather/v1/partly_clear.svg",
  "03d": "https://maps.gstatic.com/weather/v1/mostly_cloudy.svg",
  "03n": "https://maps.gstatic.com/weather/v1/mostly_cloudy.svg",
  "04d": "https://maps.gstatic.com/weather/v1/cloudy.svg",
  "04n": "https://maps.gstatic.com/weather/v1/cloudy.svg",
  "09d": "https://maps.gstatic.com/weather/v1/showers.svg",
  "09n": "https://maps.gstatic.com/weather/v1/showers.svg",
  "10d": "https://maps.gstatic.com/weather/v1/scattered_showers.svg",
  "10n": "https://maps.gstatic.com/weather/v1/scattered_showers.svg",
  "11d": "https://maps.gstatic.com/weather/v1/strong_tstorms.svg",
  "11n": "https://maps.gstatic.com/weather/v1/strong_tstorms.svg",
  "13d": "https://maps.gstatic.com/weather/v1/snow_showers.svg",
  "13n": "https://maps.gstatic.com/weather/v1/snow_showers.svg",
  "50d": "https://maps.gstatic.com/weather/v1/dust.svg",
  "50n": "https://maps.gstatic.com/weather/v1/dust.svg",
};